version: '2'
services:
  jupyter:
    container_name: jupyter-openu
    image: mega1arbuz/jupyter:jupyter-nbe-numpy
    environment:
      - JUPYTER_TOKEN=12345abcd
    ports:
      - "8888:8888"
    volumes:
      - ./work:/home/jovyan/work
